name: clonezilla-docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REPO: ${{ vars.DOCKER_USERNAME }}/clonezilla
  URL: https://sourceforge.net/projects/clonezilla/files/clonezilla_live_stable/3.2.1-28/clonezilla-live-3.2.1-28-amd64.iso
  UPLOAD_LATEST: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Container
        run: |
          TMPDIR=$(mktemp -d)
          sudo ./src/main/scripts/build.sh --dir=${TMPDIR} --url=${URL} --docker-repo=${DOCKER_REPO}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Container
        shell: bash
        run: |
          docker images
          [ "${UPLOAD_LATEST}" = false ] && docker rmi ${DOCKER_REPO}:latest
          docker push ${DOCKER_REPO} --all-tags
        if: github.ref == 'refs/heads/main'
